/**
* @description Utility Constant Class for Strings
* @revision
*			02.25.2021 - Afrancisco - Initial creation
**/
global class UtilityConstant {
	public static String PARTICIPANT_STATUS_INVITED = 'Invited';
    public static String PARTICIPANT_STATUS_RESPONDED = 'Responded';
    
    public static String EMAIL_TEMPLATE_INVITATION_NAME = 'Event_Invitation_Template';
    public static String EMAIL_TEMPLATE_CONFIRMATION_NAME = 'Event_Confirmation_Template';
    
}