public inherited sharing class SO_Constants {
  Public static final String CALLOUTOPERATION   = 'CALLOUTOPERATION';
  Public static final String NAMEDCREDENTIAL    = 'NAMEDCREDENTIAL';
  Public static final String PROVIDERFACTORY    = 'PROVIDERFACTORY';
  Public static final String RESTHTTPVERB       = 'RESTHTTPVERB';
  Public static final String RESTPATH           = 'RESTPATH';
  Public static final String RESTQUERY          = 'RESTQUERY';
  Public static final String RESTBODY           = 'RESTBODY';
  Public static final String RESTHEADERS        = 'RESTHEADERS';
  Public static final String SERVICERESPONSE    = 'SERVICERESPONSE';
  Public static final String SERVICETIMEOUT     = 'SERVICETIMEOUT';  // In milliseconds, max 120000
  Public static final Set<String> HTTPVERBSET   = new Set<String>{'GET','POST','PATCH','PUT','HEAD','DELETE'};
}